[project]
name = "reweld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
    "pylint>=3.3.7",
    "pytest>=8.3.5",
]
